### ISSUE TITLE
ALARM signal

### ISSUE THREAD

**Issue by ovidiu-mura** [omgbrbttyl/SignalHandlers#1]
I'll will implement a C program ALARM signal example.

**Comment by omgbrbttyl** [comment]
Great. When you add your code and it is compiled into the library, I will close the issue for it.

**Comment by ovidiu-mura** [comment]
[alarm.zip](https://github.com/omgbrbttyl/SignalHandlers/files/3438868/alarm.zip)

**Comment by ovidiu-mura** [comment]
I cannot check-in code to the repo.  I get the error below:

`mura@ada:~/classes/cs510-alsp/alarm/SignalHandlers$ git push origin master
Username for 'https://github.com': mura@pdx.edu
Password for 'https://mura@pdx.edu@github.com':
remote: Permission to omgbrbttyl/SignalHandlers.git denied to ovidiu-mura.
fatal: unable to access 'https://github.com/omgbrbttyl/SignalHandlers.git/': The requested URL returned error: 403`

**Comment by omgbrbttyl** [comment]
I added in your code. I'll talk to the class Monday, you should have been able to just merge your code with the repo. Thanks for making it.

**Comment by omgbrbttyl** [comment]
Code was added to repo, compiles/runs correctly, linked in with library. SIGALRM finished and closed.
